### ISSUE TITLE
Compilation error (missing file?)

### ISSUE THREAD

**Issue by kkar** [quilkin/WhereIAm#1]
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS2001	Source file 'C:\Projects\WhereIAm-master\WebMap\Connect.cs' could not be found.	WebMap	C:\Projects\WhereIAm-master\WebMap\CSC	1	Active
>

**Comment by kkar** [comment]
anything?

**Comment by quilkin** [comment]
I removed this file from GitHub because it has password info for my database.  Are you able to download the rest of the project OK or does this error prevent it?
Here's the content of connect.cs:
`namespace WebMap
{
    public class Connections
    {
        public static string connection = "server=www.timetrials.org.uk;database=??????????;User ID=??????????;Password=??????????";        public static string smtpserver = "mail.quilkin.co.uk";
        public static string smtpUserName = "admin@quilkin.co.uk";
        public static string smtpPassword = "";
    }
}`
