### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by kkar** [quilkin/WhereIAm#2]
Thanks again for this beautiful example on xamarin, and sorry for openning issues one after another! I just want to re-make the server part by using PHP and i am probably missing the schema of the database. Is there a possibility to have it in the repository as an update or something? Thanks!

**Comment by quilkin** [comment]
My database is used for several projects (I'm only allowed one SQL database by my service provider!) but the only tables relevant to (and required by) the location project are below. Hope that's OK for you!

`CREATE TABLE [dbo].[logins] (
    [Id]     INT           IDENTITY (1, 1) NOT NULL,
    [name]   NCHAR (10)    NOT NULL,
    [pw]     NCHAR (10)    NOT NULL,
    [email]  NVARCHAR (50) NULL,
    [role]   INT           DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_logins] PRIMARY KEY CLUSTERED ([Id] ASC)
);

CREATE TABLE [dbo].[locations] (
    [lat]   DECIMAL (10, 6) DEFAULT ((0)) NOT NULL,
    [lon]   DECIMAL (10, 6) DEFAULT ((0)) NOT NULL,
    [dt]    SMALLDATETIME   NULL,
    [id]    INT             IDENTITY (1, 1) NOT NULL,
    [owner] INT             NULL
);`
